/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Michael V (https://sketchfab.com/bossdeff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-room-a149d5bfcef6496c9a0606b5ce5ebf27
Title: Sci-Fi Computer Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ComputerRoom = (props) => {
  const { nodes, materials } = useGLTF('/models/sci-fi_computer_room.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh
          name="Object_2"
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Desk_1}
        />
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Posters}
        />
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Keyboard}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.speaker_2}
        />
        {/* <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.BG_Dark}
        /> */}
        {/* <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Carpet}
        /> */}
        {/* <mesh
          name="Object_8"
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Emission}
        /> */}
        <mesh
          name="Object_9"
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Emission_Blue}
        />
        {/* <mesh
          name="Object_10"
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Foam_Acoustic}
        /> */}
        {/* <mesh
          name="Object_11"
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.Foam_Acoustic}
        /> */}
        {/* <mesh
          name="Object_12"
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Trim_Sheet_Wall}
        /> */}
        <mesh
          name="Object_13"
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Monitor_Single}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_computer_room.glb')

export default ComputerRoom